--#[distinct-00]
SELECT DISTINCT a FROM T;

--#[distinct-01]
SELECT DISTINCT * FROM T;

--#[distinct-02]
(SELECT DISTINCT a FROM T UNION SELECT DISTINCT a FROM T);

--#[distinct-03]
(SELECT DISTINCT a FROM T UNION SELECT a FROM T);

--#[distinct-04]
(SELECT a FROM T UNION SELECT DISTINCT a FROM T);
