-- INTERVAL <interval string> <single datetime field>
--#[interval-00]
SELECT INTERVAL '10' YEAR AS i FROM T;

--#[interval-01]
SELECT INTERVAL '-10' YEAR AS i FROM T;

--#[interval-02]
SELECT INTERVAL '10' YEAR (2) AS i FROM T;

--#[interval-03]
SELECT INTERVAL '-10' YEAR (2) AS i FROM T;

--#[interval-04]
SELECT INTERVAL '10' MONTH AS i FROM T;

--#[interval-05]
SELECT INTERVAL '-10' MONTH AS i FROM T;

--#[interval-06]
SELECT INTERVAL '10' MONTH (2) AS i FROM T;

--#[interval-07]
SELECT INTERVAL '-10' MONTH (2) AS i FROM T;

--#[interval-08]
SELECT INTERVAL '10' DAY AS i FROM T;

--#[interval-09]
SELECT INTERVAL '-10' DAY AS i FROM T;

--#[interval-10]
SELECT INTERVAL '10' DAY (2) AS i FROM T;

--#[interval-11]
SELECT INTERVAL '-10' DAY (2) AS i FROM T;

--#[interval-12]
SELECT INTERVAL '10' HOUR AS i FROM T;

--#[interval-13]
SELECT INTERVAL '-10' HOUR AS i FROM T;

--#[interval-14]
SELECT INTERVAL '10' HOUR (2) AS i FROM T;

--#[interval-15]
SELECT INTERVAL '-10' HOUR (2) AS i FROM T;

--#[interval-16]
SELECT INTERVAL '10' MINUTE AS i FROM T;

--#[interval-17]
SELECT INTERVAL '-10' MINUTE AS i FROM T;

--#[interval-18]
SELECT INTERVAL '10' MINUTE (2) AS i FROM T;

--#[interval-19]
SELECT INTERVAL '-10' MINUTE (2) AS i FROM T;

--#[interval-20]
SELECT INTERVAL '10' SECOND AS i FROM T;

--#[interval-21]
SELECT INTERVAL '-10' SECOND AS i FROM T;

--#[interval-22]
SELECT INTERVAL '10' SECOND (2) AS i FROM T;

--#[interval-23]
SELECT INTERVAL '-10' SECOND (2) AS i FROM T;

--#[interval-24]
SELECT INTERVAL '10.234' SECOND (2, 3) AS i FROM T;

--#[interval-25]
SELECT INTERVAL '-10.234' SECOND (2, 3) AS i FROM T;

-- <start field> TO <end field>
--#[interval-26]
SELECT INTERVAL '10-3' YEAR TO MONTH AS i FROM T;

--#[interval-27]
SELECT INTERVAL '-10-3' YEAR TO MONTH AS i FROM T;

--#[interval-28]
SELECT INTERVAL '10-3' YEAR (2) TO MONTH AS i FROM T;

--#[interval-29]
SELECT INTERVAL '-10-3' YEAR (2) TO MONTH AS i FROM T;

--#[interval-30]
SELECT INTERVAL '10 3' DAY TO HOUR AS i FROM T;

--#[interval-31]
SELECT INTERVAL '-10 3' DAY TO HOUR AS i FROM T;

--#[interval-32]
SELECT INTERVAL '10 3' DAY (2) TO HOUR AS i FROM T;

--#[interval-33]
SELECT INTERVAL '-10 3' DAY (2) TO HOUR AS i FROM T;

--#[interval-34]
SELECT INTERVAL '10 3:4' DAY TO MINUTE AS i FROM T;

--#[interval-35]
SELECT INTERVAL '-10 3:4' DAY TO MINUTE AS i FROM T;

--#[interval-36]
SELECT INTERVAL '10 3:4' DAY (2) TO MINUTE AS i FROM T;

--#[interval-37]
SELECT INTERVAL '-10 3:4' DAY (2) TO MINUTE AS i FROM T;

--#[interval-38]
SELECT INTERVAL '10 3:4:5' DAY TO SECOND AS i FROM T;

--#[interval-39]
SELECT INTERVAL '-10 3:4:5' DAY TO SECOND AS i FROM T;

--#[interval-40]
SELECT INTERVAL '10 3:4:5' DAY (2) TO SECOND AS i FROM T;

--#[interval-41]
SELECT INTERVAL '-10 3:4:5' DAY (2) TO SECOND AS i FROM T;

--#[interval-42]
SELECT INTERVAL '10 3:4:5.678' DAY TO SECOND (3) AS i FROM T;

--#[interval-43]
SELECT INTERVAL '-10 3:4:5.678' DAY TO SECOND (3) AS i FROM T;

--#[interval-44]
SELECT INTERVAL '10 3:4:5.678' DAY (2) TO SECOND (3) AS i FROM T;

--#[interval-45]
SELECT INTERVAL '-10 3:4:5.678' DAY (2) TO SECOND (3) AS i FROM T;

--#[interval-46]
SELECT INTERVAL '3:4' HOUR TO MINUTE AS i FROM T;

--#[interval-47]
SELECT INTERVAL '-3:4' HOUR TO MINUTE AS i FROM T;

--#[interval-48]
SELECT INTERVAL '3:4' HOUR (2) TO MINUTE AS i FROM T;

--#[interval-49]
SELECT INTERVAL '-3:4' HOUR (2) TO MINUTE AS i FROM T;

--#[interval-50]
SELECT INTERVAL '2:3:4' HOUR TO SECOND AS i FROM T;

--#[interval-51]
SELECT INTERVAL '-2:3:4' HOUR TO SECOND AS i FROM T;

--#[interval-52]
SELECT INTERVAL '2:3:4' HOUR (2) TO SECOND AS i FROM T;

--#[interval-53]
SELECT INTERVAL '-2:3:4' HOUR (2) TO SECOND AS i FROM T;

--#[interval-54]
SELECT INTERVAL '2:3:4.567' HOUR TO SECOND (3) AS i FROM T;

--#[interval-55]
SELECT INTERVAL '-2:3:4.567' HOUR TO SECOND (3) AS i FROM T;

--#[interval-56]
SELECT INTERVAL '2:3:4.567' HOUR (2) TO SECOND (3) AS i FROM T;

--#[interval-57]
SELECT INTERVAL '-2:3:4.567' HOUR (2) TO SECOND (3) AS i FROM T;

--#[interval-58]
SELECT INTERVAL '3:4' MINUTE TO SECOND AS i FROM T;

--#[interval-59]
SELECT INTERVAL '-3:4' MINUTE TO SECOND AS i FROM T;

--#[interval-60]
SELECT INTERVAL '3:4' MINUTE (2) TO SECOND AS i FROM T;

--#[interval-61]
SELECT INTERVAL '-3:4' MINUTE (2) TO SECOND AS i FROM T;

--#[interval-62]
SELECT INTERVAL '3:4.567' MINUTE TO SECOND (3) AS i FROM T;

--#[interval-63]
SELECT INTERVAL '-3:4.567' MINUTE TO SECOND (3) AS i FROM T;

--#[interval-64]
SELECT INTERVAL '3:4.567' MINUTE (2) TO SECOND (3) AS i FROM T;

--#[interval-65]
SELECT INTERVAL '-3:4.567' MINUTE (2) TO SECOND (3) AS i FROM T;

-- Additional DAY TO SECOND precision tests
--#[interval-66]
SELECT INTERVAL '2 3:4:5.000006' DAY TO SECOND (6) AS i FROM T;

--#[interval-67]
SELECT INTERVAL '-2 3:4:5.000006' DAY TO SECOND (6) AS i FROM T;

--#[interval-68]
SELECT INTERVAL '2 3:4:5.000006' DAY TO SECOND (9) AS i FROM T;

--#[interval-69]
SELECT INTERVAL '-2 3:4:5.000006' DAY TO SECOND (9) AS i FROM T;

--#[interval-70]
SELECT INTERVAL '2 3:4:5.000006' DAY TO SECOND (3) AS i FROM T;

--#[interval-71]
SELECT INTERVAL '-2 3:4:5.000006' DAY TO SECOND (3) AS i FROM T;

--#[interval-72]
SELECT INTERVAL '2 3:4:5.000000006' DAY TO SECOND (6) AS i FROM T;

--#[interval-73]
SELECT INTERVAL '-2 3:4:5.000000006' DAY TO SECOND (6) AS i FROM T;