--#[limit-offset-00]
SELECT a FROM T LIMIT 1;

--#[limit-offset-01]
SELECT a FROM T OFFSET 1;

--#[limit-offset-02]
SELECT a FROM T LIMIT 1 OFFSET 1;

--#[limit-offset-03]
(SELECT a FROM T LIMIT 1 OFFSET 2) UNION (SELECT a FROM T LIMIT 3 OFFSET 4);

--#[limit-offset-04]
(SELECT a FROM T LIMIT 1 OFFSET 2) EXCEPT (SELECT a FROM T LIMIT 3 OFFSET 4);

--#[limit-offset-05]
(SELECT a FROM T LIMIT 1 OFFSET 2) INTERSECT (SELECT a FROM T LIMIT 3 OFFSET 4);

--#[limit-offset-06]
(SELECT a FROM T LIMIT 1 OFFSET 2) UNION DISTINCT (SELECT a FROM T LIMIT 3 OFFSET 4);

--#[limit-offset-07]
(SELECT a FROM T LIMIT 1 OFFSET 2) EXCEPT DISTINCT (SELECT a FROM T LIMIT 3 OFFSET 4);

--#[limit-offset-08]
(SELECT a FROM T LIMIT 1 OFFSET 2) INTERSECT DISTINCT (SELECT a FROM T LIMIT 3 OFFSET 4);

--#[limit-offset-09]
(SELECT a FROM T LIMIT 1 OFFSET 2) UNION ALL (SELECT a FROM T LIMIT 3 OFFSET 4);

--#[limit-offset-10]
(SELECT a FROM T LIMIT 1 OFFSET 2) EXCEPT ALL (SELECT a FROM T LIMIT 3 OFFSET 4);

--#[limit-offset-11]
(SELECT a FROM T LIMIT 1 OFFSET 2) INTERSECT ALL (SELECT a FROM T LIMIT 3 OFFSET 4);

--#[limit-offset-12]
(SELECT a FROM T LIMIT 1 OFFSET 2) UNION (SELECT a FROM T LIMIT 3 OFFSET 4) LIMIT 5 OFFSET 6;

--#[limit-offset-13]
(SELECT a FROM T LIMIT 1 OFFSET 2) EXCEPT (SELECT a FROM T LIMIT 3 OFFSET 4) LIMIT 5 OFFSET 6;

--#[limit-offset-14]
(SELECT a FROM T LIMIT 1 OFFSET 2) INTERSECT (SELECT a FROM T LIMIT 3 OFFSET 4) LIMIT 5 OFFSET 6;

--#[limit-offset-15]
(SELECT a FROM T LIMIT 1 OFFSET 2) UNION DISTINCT (SELECT a FROM T LIMIT 3 OFFSET 4) LIMIT 5 OFFSET 6;

--#[limit-offset-16]
(SELECT a FROM T LIMIT 1 OFFSET 2) EXCEPT DISTINCT (SELECT a FROM T LIMIT 3 OFFSET 4) LIMIT 5 OFFSET 6;

--#[limit-offset-17]
(SELECT a FROM T LIMIT 1 OFFSET 2) INTERSECT DISTINCT (SELECT a FROM T LIMIT 3 OFFSET 4) LIMIT 5 OFFSET 6;

--#[limit-offset-18]
(SELECT a FROM T LIMIT 1 OFFSET 2) UNION ALL (SELECT a FROM T LIMIT 3 OFFSET 4) LIMIT 5 OFFSET 6;

--#[limit-offset-19]
(SELECT a FROM T LIMIT 1 OFFSET 2) EXCEPT ALL (SELECT a FROM T LIMIT 3 OFFSET 4) LIMIT 5 OFFSET 6;

--#[limit-offset-20]
(SELECT a FROM T LIMIT 1 OFFSET 2) INTERSECT ALL (SELECT a FROM T LIMIT 3 OFFSET 4) LIMIT 5 OFFSET 6;
